### ISSUE TITLE
TLS1v2 Warning does not work with ruby 2.2.3

### ISSUE THREAD

**Issue by odesu** [paypal/sdk-core-ruby#30]
The lines within the file sdk-core-ruby/lib/paypal-sdk/core/util/http_helper.rb ...

    begin
      https.ssl_version = :TLSv1_2
    rescue => error
      logger.warn("WARNING: Your system does not support TLSv1.2. Per PCI Security Council mandate (https://github.com/paypal/TLS-update), you MUST update to latest security library.")
    end

...do not work within ruby 2.2.3 as you might have intended. If the system does not support TLSv1.2 the exception is not raised when setting the ssl version. The exception is thrown when you start the http request. Meaning no warning is thrown and the gem breaks when running on a system without TLSv1.2 support.

**Comment by juwlee** [comment]
@odesu thanks for reporting. Can you please try out `v0.3.5`? It actually makes a call to test endpoint to verify TLS 1.2 support. You can get the gem like the following:
`gem 'paypal-sdk-core', :git => "https://github.com/paypal/sdk-core-ruby.git", :branch => 'v0.3.5'`

**Comment by juwlee** [comment]
Also, what is your environment like? Ruby version, OPENSSL version. OS?

**Comment by odesu** [comment]
Our environment:

* ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-linux]
* debian 6.0.7
* openssl 0.9.8

To solve the problem we updated to openssl 1.0.1 which supports tls 1.2 and recompiled ruby. afterwars everything worked fine for us.

I'll try to test the scenario with the new branch today.

**Comment by juwlee** [comment]
:+1: Thanks @odesu

**Comment by esb** [comment]
This broke my system running 0.3.4 with Ruby 2.1.5 and a version of OpenSSL that doesn't support TLS 1.2.

I rolled back to 0.3.2 to keep the server running and am rebuilding Ruby to include the latest version of OpenSSL.

It would have been nice if this update could have been tested on a system that doesn't support TLS 1.2 before releasing it to the world and breaking our production systems.
